// Generates, from scripts/cells.ts:
//   solutions/vercel-mongodb-ai-memory-lab.ipynb   every answer filled in
//   labs/vercel-mongodb-ai-memory-lab.ipynb        each /*▶*/ … /*◀*/ span replaced by <CODE_BLOCK_n>
//   scripts/lab.ts                         the solution's code cells concatenated, for `deno check` / headless runs
//   instruqt/code-blocks/challenge-N.md    the Instruqt answer sheet for each challenge
//
// Deriving the lab from the solution means the two never drift, and blank numbering is contiguous.
//
// Run:  deno task build
//       deno task build --track=<path to instruqt track dir>   also rewrites the CODE_BLOCK section of each
//                                                              challenge's assignment.md, between the
//                                                              <!-- CODE_BLOCKS:START --> / END markers
import { cells } from './cells.ts'

const ROOT = new URL('../', import.meta.url)
const NOTEBOOK = 'vercel-mongodb-ai-memory-lab.ipynb'
const BLANK = /\/\*▶\*\/([\s\S]*?)\/\*◀\*\//g

// Which challenge each notebook Part belongs to. Keep in step with the Instruqt track's challenges
// (currently one challenge: kernel state does not survive a challenge switch).
const CHALLENGE_OF_PART: Record<number, number> = { 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1 }
const EXPECTED_BLANKS = 14

type Blank = { n: number; challenge: number; answer: string }

// Lines after the first keep their source indentation; strip the common part so answers paste cleanly.
const dedent = (snippet: string) => {
  const [first, ...rest] = snippet.trim().split('\n')
  const indents = rest.filter((l) => l.trim()).map((l) => l.match(/^ */)![0].length)
  const cut = indents.length ? Math.min(...indents) : 0
  return [first, ...rest.map((l) => l.slice(cut))].join('\n')
}

// ── Walk the cells once, producing both variants ────────────────────────────
const blanks: Blank[] = []
let part = 0
const solutionCells: { type: string; source: string }[] = []
const labCells: { type: string; source: string }[] = []

for (const cell of cells) {
  const heading = cell.type === 'markdown' ? cell.source.match(/^## Part (\d+)/m) : null
  if (heading) part = Number(heading[1])

  if (cell.type !== 'code') {
    solutionCells.push(cell)
    labCells.push(cell)
    continue
  }
  solutionCells.push({ type: 'code', source: cell.source.replace(BLANK, '$1') })
  labCells.push({
    type: 'code',
    source: cell.source.replace(BLANK, (_m, answer: string) => {
      const challenge = CHALLENGE_OF_PART[part]
      if (!challenge) throw new Error(`Blank in Part ${part}, which has no challenge mapping`)
      const n = blanks.length + 1
      blanks.push({ n, challenge, answer: dedent(answer) })
      return `<CODE_BLOCK_${n}>`
    }),
  })
}

for (const c of solutionCells) {
  if (c.source.includes('/*▶*/') || c.source.includes('/*◀*/')) throw new Error('Unbalanced blank marker:\n' + c.source)
}
if (blanks.length !== EXPECTED_BLANKS) throw new Error(`Expected ${EXPECTED_BLANKS} blanks, found ${blanks.length}`)

// ── Notebooks ───────────────────────────────────────────────────────────────
const toLines = (src: string) => {
  const lines = src.replace(/^\n/, '').replace(/\n$/, '').split('\n')
  return lines.map((l, i) => (i < lines.length - 1 ? l + '\n' : l))
}

const notebook = (list: { type: string; source: string }[]) => ({
  cells: list.map((c) => ({
    cell_type: c.type,
    metadata: {},
    source: toLines(c.source),
    ...(c.type === 'code' ? { execution_count: null, outputs: [] } : {}),
  })),
  metadata: {
    kernelspec: { display_name: 'Deno', language: 'typescript', name: 'deno' },
    language_info: {
      name: 'typescript',
      file_extension: '.ts',
      mimetype: 'text/x.typescript',
      codemirror_mode: 'typescript',
      nbconvert_exporter: 'script',
      pygments_lexer: 'typescript',
    },
  },
  nbformat: 4,
  nbformat_minor: 5,
})

for (const [dir, list] of [['solutions', solutionCells], ['labs', labCells]] as const) {
  await Deno.mkdir(new URL(`${dir}/`, ROOT), { recursive: true })
  await Deno.writeTextFile(new URL(`${dir}/${NOTEBOOK}`, ROOT), JSON.stringify(notebook(list), null, 1) + '\n')
  console.log(`wrote ${dir}/${NOTEBOOK} (${list.length} cells)`)
}

// ── Headless script (solution) ──────────────────────────────────────────────
const codeCells = solutionCells.filter((c) => c.type === 'code')
const lab = [
  '// AUTO-GENERATED by scripts/build-notebook.ts — do not edit. Edit scripts/cells.ts instead.',
  `// Contains every code cell of solutions/${NOTEBOOK} in order.`,
  '// Run:  deno task lab',
  '',
  ...codeCells.map((c, i) => `// ══════════ cell ${i + 1} ══════════\n${c.source.trim()}\n`),
].join('\n')
await Deno.writeTextFile(new URL('scripts/lab.ts', ROOT), lab)
console.log(`wrote scripts/lab.ts (${codeCells.length} code cells)`)

// ── Instruqt answer sheets ──────────────────────────────────────────────────
const challenges = [...new Set(Object.values(CHALLENGE_OF_PART))]
const sheets = new Map<number, string>()
for (const ch of challenges) {
  const mine = blanks.filter((b) => b.challenge === ch)
  sheets.set(
    ch,
    mine.length === 0
      ? 'This challenge has no code blocks to fill in: run the cells as they are.\n'
      : mine.map((b) => `CODE_BLOCK_${b.n}\n===\n\`\`\`typescript\n${b.answer}\n\`\`\`\n`).join('\n'),
  )
}
await Deno.mkdir(new URL('instruqt/code-blocks/', ROOT), { recursive: true })
for (const [ch, sheet] of sheets) {
  await Deno.writeTextFile(new URL(`instruqt/code-blocks/challenge-${ch}.md`, ROOT), sheet)
}
console.log(`wrote instruqt/code-blocks/challenge-{${challenges.join(',')}}.md (${blanks.length} blocks)`)

// Optional: sync straight into the track's assignment.md files (challenge dirs are sorted, 01-…, 02-…).
const trackArg = Deno.args.find((a) => a.startsWith('--track='))
if (trackArg) {
  const trackDir = trackArg.slice('--track='.length).replace(/\/$/, '')
  const dirs = [...Deno.readDirSync(trackDir)].filter((e) => e.isDirectory && /^\d\d-/.test(e.name)).map((e) => e.name).sort()
  for (const [ch, sheet] of sheets) {
    const dir = dirs[ch - 1]
    if (!dir) throw new Error(`No challenge directory for challenge ${ch} in ${trackDir}`)
    const path = `${trackDir}/${dir}/assignment.md`
    const text = await Deno.readTextFile(path)
    const re = /(<!-- CODE_BLOCKS:START -->\n)[\s\S]*?(<!-- CODE_BLOCKS:END -->)/
    if (!re.test(text)) throw new Error(`${path} has no CODE_BLOCKS markers`)
    await Deno.writeTextFile(path, text.replace(re, `$1\n${sheet}\n$2`))
    console.log(`synced ${path}`)
  }
}
