// AUTO-GENERATED by scripts/build-notebook.ts — do not edit. Edit scripts/cells.ts instead.
// Contains every code cell of solutions/vercel-mongodb-ai-memory-lab.ipynb in order.
// Run:  deno task lab

// ══════════ cell 1 ══════════
import { load } from '@std/dotenv'
import { ToolLoopAgent, embed, gateway, isLoopFinished, tool, type ModelMessage } from 'ai'
import { z } from 'zod'
import { MongoClient } from 'mongodb'
import { createMongoDBMemory } from '@mongodb-developer/vercel-ai-memory'

// Hosted lab: /etc/lab-env. Laptop: .env in the lab folder (the notebook sits one level down, in labs/).
// Variables that are already set always win.
for (const envPath of ['/etc/lab-env', '../.env', '.env']) await load({ envPath, export: true })

const MONGODB_URI = Deno.env.get('MONGODB_URI')
const AI_GATEWAY_API_KEY = Deno.env.get('AI_GATEWAY_API_KEY')
if (!MONGODB_URI || !AI_GATEWAY_API_KEY) throw new Error('Set MONGODB_URI and AI_GATEWAY_API_KEY (copy .env.example → .env)')

// ── Models ───────────────────────────────────────────────────────────────────
// Both go through Vercel AI Gateway: a model is just a 'provider/model' string.
const CHAT_MODEL = Deno.env.get('CHAT_MODEL') ?? 'google/gemini-3.5-flash-lite'
// Voyage AI 4 Lite — MongoDB's embedding models.
const EMBED_MODEL = 'voyage/voyage-4-lite'
const embedder = gateway.embeddingModel(EMBED_MODEL)

// Everything this lab writes goes into this database so cleanup is one call.
const DB_NAME = 'trailhead_lab'

// ── MongoDB ──────────────────────────────────────────────────────────────────
const mongo = new MongoClient(MONGODB_URI, { appName: 'devrel-workshop-trailhead-memory' })
const labDb = mongo.db(DB_NAME)
// Check the connection: run the `ping` command against the `admin` database.
await mongo.db('admin').command({ ping: 1 })

console.log('✅ MongoDB reachable — chat:', CHAT_MODEL, '| embeddings:', EMBED_MODEL, '| db:', DB_NAME)

// ══════════ cell 2 ══════════
const TRAILS = [
  { name: 'Bear Lake Loop', city: 'Denver', difficulty: 'easy', miles: 0.8, elevationGainFt: 45, notes: 'Flat, paved sections; great for knees.' },
  { name: 'Emerald Lake Trail', city: 'Denver', difficulty: 'moderate', miles: 3.2, elevationGainFt: 700, notes: 'Three alpine lakes.' },
  { name: 'Longs Peak Keyhole Route', city: 'Denver', difficulty: 'hard', miles: 14.5, elevationGainFt: 5100, notes: 'Class 3 scramble. Alpine start.' },
  { name: 'Lands End Trail', city: 'San Francisco', difficulty: 'easy', miles: 3.4, elevationGainFt: 500, notes: 'Coastal views, well graded.' },
  { name: 'Dipsea Trail', city: 'San Francisco', difficulty: 'hard', miles: 7.4, elevationGainFt: 2200, notes: 'Famous stairs. Steep.' },
  { name: 'Walden Pond Loop', city: 'Boston', difficulty: 'easy', miles: 1.7, elevationGainFt: 50, notes: 'Flat lakeside loop.' },
] as const

const suggestTrail = tool({
  description: 'Look up hiking trails near a city, optionally filtered by difficulty.',
  inputSchema: z.object({
    city: z.string().describe('City to search near, e.g. "Denver"'),
    difficulty: z.enum(['easy', 'moderate', 'hard']).optional(),
  }),
  execute: async ({ city, difficulty }) => {
    const hits = TRAILS.filter((t) => t.city.toLowerCase() === city.toLowerCase() && (!difficulty || t.difficulty === difficulty))
    return { city, count: hits.length, trails: hits }
  },
})

console.log('✅ suggestTrail tool defined over', TRAILS.length, 'trails')

// ══════════ cell 3 ══════════
const TRAILHEAD_INSTRUCTIONS = `You are Trailhead, a friendly and concise personal outdoor-trip planner.
Use the suggestTrail tool to look up real trails. Keep answers under 120 words.
If you don't know where the user is or what they can handle, ask.`

const trailhead = new ToolLoopAgent({
  model: CHAT_MODEL,
  instructions: TRAILHEAD_INSTRUCTIONS,
  tools: { suggestTrail },
  stopWhen: isLoopFinished(),
})

// deno-lint-ignore no-explicit-any
async function chat(agent: { generate: (o: any) => PromiseLike<any> }, prompt: string, extra: Record<string, unknown> = {}) {
  console.log(`\n👤 ${prompt}`)
  // Mode B passes the restored history as `messages`; the SDK takes either a prompt or messages, not both.
  const result = await agent.generate('messages' in extra ? extra : { prompt, ...extra })
  for (const step of result.steps) {
    for (const call of step.toolCalls) {
      console.log(`   🔧 ${call.toolName}(${JSON.stringify(call.input)})`)
    }
  }
  console.log(`🤖 ${result.text}`)
  return result
}

console.log('✅ Trailhead agent ready')

// ══════════ cell 4 ══════════
await chat(trailhead, "Hi! I'm Alice, I live in Denver. I love hiking, but I have bad knees so nothing steep please.")

// ══════════ cell 5 ══════════
await chat(trailhead, 'Great — can you suggest a trail for me this weekend?')

// ══════════ cell 6 ══════════
const trailheadOtherModel = new ToolLoopAgent({
  model: 'openai/gpt-4o-mini',   // ← only this line changed: a different provider, same Gateway
  instructions: TRAILHEAD_INSTRUCTIONS,
  tools: { suggestTrail },
  stopWhen: isLoopFinished(),
})
await chat(trailheadOtherModel, 'Can you suggest a trail for me this weekend?')

// ══════════ cell 7 ══════════
// Create the memory instance. It needs three things: the connection string (`uri`), the `embedder`
// defined in Part 1, and a `topology` whose `dbName` is DB_NAME so every tier lands in the lab database.
const mongodbMemory = createMongoDBMemory({
  uri: MONGODB_URI,
  embedder,
  topology: { dbName: DB_NAME },
})

// Bootstrap now — collections, TTL indexes and Vector Search indexes — instead of on the first tool call.
await mongodbMemory.connect()

// Calling the instance returns a tools record scoped to a user + session: user 'alice', session 'alice-s1'.
const aliceTools = mongodbMemory({ userId: 'alice', sessionId: 'alice-s1' })
console.log('tool keys:', Object.keys(aliceTools))
console.log('\n── tool description the LLM sees ──\n' + aliceTools.memory.description)

// ══════════ cell 8 ══════════
async function describeDb() {
  // List every collection in `labDb` as an array.
  const cols = (await labDb.listCollections().toArray()).map((c) => c.name).sort()
  console.log('collections:', cols)
  for (const name of cols) {
    const col = labDb.collection(name)
    const count = await col.countDocuments()
    // Get the collection's indexes and keep only the TTL ones (they have an `expireAfterSeconds` field).
    const ttl = (await col.indexes()).filter((i) => 'expireAfterSeconds' in i).map((i) => `${Object.keys(i.key)[0]}(${i.expireAfterSeconds}s)`)
    // List the collection's Atlas Search / Vector Search indexes as an array.
    // deno-lint-ignore no-explicit-any
    const vec = (await col.listSearchIndexes().toArray()) as any[]
    const vecInfo = vec.map((v) => `${v.name} [${v.status}] dims=${v.latestDefinition?.fields?.[0]?.numDimensions ?? '?'}`)
    console.log(`  ${name.padEnd(20)} docs=${String(count).padEnd(3)} ttl=${ttl.join(',').padEnd(40)} vector=${vecInfo.join(', ') || '—'}`)
  }
}
await describeDb()

// ══════════ cell 9 ══════════
const MEMORY_INSTRUCTIONS = `
You have a persistent \`memory\` tool.
- At the start of every reply, call session_recent to restore the conversation, then semantic_search for facts about the user relevant to their message.
- When the user tells you facts about themselves (name, location, preferences, constraints, health), save each with semantic_save (name = the entity, e.g. "Alice"; importance 7-9 for constraints like injuries).
- When the user reports something that happened (a hike they did, a rating), record it with episodic_save.
- Persist the conversation with session_append: once for the user's message, once for your final reply.
- If the user asks you to forget something, semantic_search for it and call memory_forget with the matching memory_type + id.
Never mention memory operations in your replies.`

function buildTrailhead(userId: string, sessionId: string) {
  return new ToolLoopAgent({
    model: CHAT_MODEL,
    instructions: TRAILHEAD_INSTRUCTIONS + '\n' + MEMORY_INSTRUCTIONS,
    // Memory is just more tools: spread the tools scoped to this userId + sessionId next to suggestTrail.
    tools: { suggestTrail, ...mongodbMemory({ userId, sessionId }) },
    stopWhen: isLoopFinished(),
  })
}

const trailheadA = buildTrailhead('alice', 'alice-s1')
console.log('✅ Trailhead (Mode A) ready — tools:', Object.keys({ suggestTrail, ...aliceTools }))

// ══════════ cell 10 ══════════
await chat(trailheadA, "Hi! I'm Alice, I live in Denver. I love hiking, but I have bad knees so nothing steep please.")

// ══════════ cell 11 ══════════
await chat(trailheadA, 'Great — can you suggest a trail for me this weekend?')

// ══════════ cell 12 ══════════
// Find every document in the `semantic_memory` collection whose `user_id` is 'alice'.
const semanticDocs = await labDb.collection('semantic_memory').find({ user_id: 'alice' }).toArray()
for (const d of semanticDocs) {
  console.log(`• [${d.name}] importance=${d.importance} is_latest=${d.is_latest} dims=${d.embedding?.length}`)
  console.log(`    "${d.description}"`)
}

// ══════════ cell 13 ══════════
const trailheadA_nextWeek = buildTrailhead('alice', 'alice-s2')   // new session, same user
await chat(trailheadA_nextWeek, 'Remind me — what did I tell you about my knees?')

// ══════════ cell 14 ══════════
const { embedding: queryVector } = await embed({ model: embedder, value: 'any joint problems I should plan around?' })

const pipeline = [
  {
    // $vectorSearch over semantic_memory: index 'semantic_vector_index', vectors in the 'embedding' field,
    // 50 candidates, top 3 results, and only Alice's current facts (user_id 'alice', is_latest true).
    $vectorSearch: {
      index: 'semantic_vector_index',
      path: 'embedding',
      queryVector,
      numCandidates: 50,
      limit: 3,
      filter: { user_id: { $eq: 'alice' }, is_latest: { $eq: true } },
    },
  },
  // Keep name and description, drop _id, and add the similarity score from the search metadata.
  { $project: { _id: 0, name: 1, description: 1, score: { $meta: 'vectorSearchScore' } } },
]

for (const hit of await labDb.collection('semantic_memory').aggregate(pipeline).toArray()) {
  console.log(`  ${hit.score.toFixed(3)}  [${hit.name}] ${hit.description}`)
}

// ══════════ cell 15 ══════════
// Find the turns of session 'alice-s1' (field `session_id`) in `session_memory`, oldest first (sort by `seq` ascending).
const sessionTurns = await labDb.collection('session_memory').find({ session_id: 'alice-s1' }).sort({ seq: 1 }).toArray()
console.log(`alice-s1 has ${sessionTurns.length} stored turn(s) for 2 user prompts + 2 replies (expected 4):`)
for (const t of sessionTurns) console.log(`  #${t.seq} ${t.role.padEnd(9)} ${t.content.slice(0, 80)}`)

// ══════════ cell 16 ══════════
const mongodbMemoryB = createMongoDBMemory({
  uri: MONGODB_URI,
  embedder,
  // Same database, but hide the session commands from the LLM: the runtime owns the transcript now.
  topology: { dbName: DB_NAME, hideToolCommands: ['session'] },
})
await mongodbMemoryB.connect()

const MEMORY_INSTRUCTIONS_B = `
You have a persistent \`memory\` tool. The conversation history is already in your context — do not try to load or save it.
- Before answering, semantic_search for facts about the user relevant to their message.
- When the user tells you facts about themselves, save each with semantic_save (importance 7-9 for constraints like injuries).
- When the user reports something that happened (a hike they did, a rating), record it with episodic_save.
- If the user asks you to forget something, semantic_search for it and call memory_forget with the matching memory_type + id.
Never mention memory operations in your replies.`

// One Mode B turn: restore → build a scoped agent → generate → persist. A serverless handler does the same per request.
async function chatB(userId: string, sessionId: string, prompt: string, extraInstructions = '') {
  // BEFORE: load this user + session's prior turns from MongoDB as ModelMessage[].
  const history: ModelMessage[] = await mongodbMemoryB.loadSession({ userId, sessionId })

  const agent = new ToolLoopAgent({
    model: CHAT_MODEL,
    instructions: [TRAILHEAD_INSTRUCTIONS, MEMORY_INSTRUCTIONS_B, extraInstructions].join('\n'),
    tools: { suggestTrail, ...mongodbMemoryB({ userId, sessionId }) },
    stopWhen: isLoopFinished(),
  })

  return chat(agent, prompt, {
    // The restored history, then this turn's prompt as a user message.
    messages: [...history, { role: 'user', content: prompt }],
    // AFTER: write every turn exactly once — the memory instance's hook, with this turn's scope baked in.
    onEnd: mongodbMemoryB.onFinish({ userId, sessionId, prompt }),
  })
}
console.log('✅ Trailhead (Mode B) ready — session commands hidden from the LLM:', Object.keys(mongodbMemoryB({ userId: 'x', sessionId: 'y' })))

// ══════════ cell 17 ══════════
await chatB('bob', 'bob-s1', "Hey, I'm Bob from San Francisco. I'm training for a trail marathon, so bring on the steep stuff.")
await chatB('bob', 'bob-s1', 'What would you suggest for Saturday?')
await chatB('bob', 'bob-s1', 'And which one did you mention first?')

// ══════════ cell 18 ══════════
// Count bob-s1's stored turns per role: $match on session_id 'bob-s1', then $group by $role with a $sum counter.
const turnsByRole = await labDb.collection('session_memory').aggregate([
  { $match: { session_id: 'bob-s1' } },
  { $group: { _id: '$role', turns: { $sum: 1 } } },
]).toArray()
console.log('bob-s1 turns by role:', Object.fromEntries(turnsByRole.map((r) => [r._id, r.turns])))

const bobTurns = await mongodbMemoryB.store.sessionRecent('bob-s1', 50)
console.log(`bob-s1: ${bobTurns.length} turns`)
for (const t of bobTurns) console.log(`  #${String(t.seq).padStart(2)} ${t.role.padEnd(9)} ${t.tool_name ? '[' + t.tool_name + '] ' : ''}${t.content.slice(0, 70).replace(/\n/g, ' ')}`)

// ══════════ cell 19 ══════════
await chatB('bob', 'bob-s1', 'Sorry, I got disconnected. What were we talking about?')

// ══════════ cell 20 ══════════
await chatB('alice', 'alice-s3', "Quick update: I did the Bear Lake Loop yesterday like you suggested. Knees were fine! I'd give it an 8/10 — a bit crowded though.")

// ══════════ cell 21 ══════════
await chatB('alice', 'alice-s4', 'Which trails have I already done, and how did I rate them?')   // yet another new session

// ══════════ cell 22 ══════════
// Find Alice's episodes in `episodic_memory`, most important first (sort by `importance` descending).
const episodes = await labDb.collection('episodic_memory').find({ user_id: 'alice' }).sort({ importance: -1 }).toArray()
for (const e of episodes) console.log(`• event_type=${e.event_type} importance=${e.importance} retrievals=${e.stats?.retrieval_ct}\n    "${e.description}"`, e.context ? JSON.stringify(e.context) : '')

// ══════════ cell 23 ══════════
const { store } = mongodbMemoryB

const noteId = await store.scratchpadWrite('alice', 'alice-s4', 'Alice mentioned Bear Lake was crowded — she may prefer quieter trails or early starts.')
console.log('scratchpad note:', String(noteId))
console.log('before promote:', (await store.scratchpadRead('alice-s4')).map((n) => ({ note: n.note.slice(0, 40) + '…', promoted: n.promoted })))

// Promote the note into episodic memory for 'alice' with event type 'preference' and importance 6.
const { episodicId } = await store.scratchpadPromote(String(noteId), 'alice', 'preference', { importance: 6 })
console.log('promoted → episodic', String(episodicId))
console.log('after promote: ', (await store.scratchpadRead('alice-s4')).map((n) => ({ note: n.note.slice(0, 40) + '…', promoted: n.promoted })))

// ══════════ cell 24 ══════════
await store.proceduralSave(
  'alice',
  'Trip briefing format',
  `When recommending a trail, always answer in this exact structure:
🥾 Trail: <name> — <miles> mi, <elevation gain> ft, <difficulty>
✅ Why it fits: <one line tied to what you know about the user>
⏰ Go early: <one practical tip>`,
  // Options: mark it as written by a person (source 'human_expert') and give it importance 9.
  { source: 'human_expert', importance: 9 },
)

await chatB('alice', 'alice-s5', 'Suggest something new for me next weekend.',
  'Before recommending any trail, call procedural_search with query "trip briefing format" and follow the procedure you find exactly.')

// ══════════ cell 25 ══════════
const showAliceFacts = async (label: string) => {
  // Find Alice's facts in `semantic_memory` in the order they were written (sort by `timestamp` ascending).
  const docs = await labDb.collection('semantic_memory').find({ user_id: 'alice' }).sort({ timestamp: 1 }).toArray()
  console.log(`\n${label} — ${docs.length} doc(s)`)
  for (const d of docs) console.log(`  [${d.name}] latest=${d.is_latest} imp=${d.importance} "${d.description.slice(0, 90)}"`)
}
await showAliceFacts('BEFORE')
await chatB('alice', 'alice-s6', "Good news — physio worked, my knees are totally fine now. I'm up for moderate trails.")
await showAliceFacts('AFTER')

// ══════════ cell 26 ══════════
await chatB('alice', 'alice-s7', "Please forget where I live — I'd rather not have my location stored.")

// Models sometimes pick the wrong id to forget, so also forget one fact from code, where the id is certain.
await store.semanticSave('alice', 'Alice gym', 'Alice has a gym membership at a Denver climbing gym.', { importance: 4 })
const gymFact = await labDb.collection('semantic_memory').findOne({ user_id: 'alice', name: 'Alice gym', is_latest: true })
// Forget that semantic memory by id with the store (the id is gymFact's _id, as a string).
await store.forget('semantic', String(gymFact!._id))

// Find Alice's facts that are scheduled for deletion: `expire_at` is set and already in the past ($lte now).
const forgotten = await labDb.collection('semantic_memory').find({ user_id: 'alice', expire_at: { $lte: new Date() } }).toArray()
console.log(`${forgotten.length} fact(s) waiting for the TTL monitor:`)
for (const d of forgotten) console.log(`  [${d.name}] expire_at=${d.expire_at.toISOString()}  "${d.description.slice(0, 70)}"`)

// ══════════ cell 27 ══════════
const TUNED_DB = DB_NAME + '_tuned'

const tunedMemory = createMongoDBMemory({
  uri: MONGODB_URI,
  embedder,
  topology: { dbName: TUNED_DB },
  retention: {
    // Low-importance facts expire after 7 days; importance ≥ 7 lives forever.
    // Use mode 'ttl+importance' — it becomes a TTL index with a partialFilterExpression on importance.
    semantic: { mode: 'ttl+importance', ttlSeconds: 7 * 86_400, minImportance: 7 },
    // Forgetting curve: lifetime doubles with each importance point, refreshed every time it's read.
    episodic: {
      mode: 'dynamic',
      refreshOnRead: true,
      computeExpireAt: ({ importance }) => new Date(Date.now() + Math.pow(2, importance) * 3600 * 1000),
    },
    session: { mode: 'ttl', ttlSeconds: 7 * 86_400 },   // keep transcripts a week instead of a day
  },
  filtering: {
    // Never surface trivia: leave memories with importance below 4 out of search results.
    minImportance: 4,
    numCandidatesMultiplier: 20, // better recall on $vectorSearch at slight cost
  },
  defaults: { searchLimit: 3 },
})
await tunedMemory.connect()

const t = tunedMemory.store
await t.semanticSave('carol', 'Carol', 'Carol is allergic to bee stings — carries an EpiPen.', { importance: 9 })
await t.semanticSave('carol', 'Carol snack', 'Carol likes trail mix with extra almonds.', { importance: 3 })
await t.episodicSave('carol', 'hike', 'Carol summited Mt. Bierstadt, felt strong.', { importance: 8 })
await t.episodicSave('carol', 'hike', 'Carol did a short walk around the block.', { importance: 2 })

const tunedDb = mongo.db(TUNED_DB)
console.log('semantic TTL indexes:', (await tunedDb.collection('semantic_memory').indexes()).filter((i) => 'expireAfterSeconds' in i).map((i) => ({ key: i.key, ttl: i.expireAfterSeconds, partial: i.partialFilterExpression })))
console.log('\nepisodic expire_at (dynamic):')
for (const e of await tunedDb.collection('episodic_memory').find({}).toArray()) {
  const hrs = e.expire_at ? Math.round((e.expire_at.getTime() - Date.now()) / 3600e3) : null
  console.log(`  imp=${e.importance} → expires in ~${hrs} h  "${e.description.slice(0, 45)}"`)
}

// ══════════ cell 28 ══════════
console.log('search "what does Carol eat on the trail?" →', (await t.semanticSearch('carol', 'what does Carol eat on the trail?')).map((d) => `[imp ${d.importance}] ${d.description}`))
console.log('search "medical conditions" →', (await t.semanticSearch('carol', 'medical conditions')).map((d) => `[imp ${d.importance}] ${d.description}`))

// ══════════ cell 29 ══════════
const tenantMemory = createMongoDBMemory({
  uri: MONGODB_URI,
  embedder,
  topology: {
    dbName: DB_NAME + '_tenants',
    collections: { semantic: 'facts', session: 'transcripts' },     // your naming
    vectorIndexNames: { semantic: 'facts_vs' },
    disable: ['scratchpad', 'procedural'],                          // tiers this product doesn't use
    // Add 'tenant_id' as an extra Vector Search filter field on the semantic and episodic tiers.
    extraFilterFields: { semantic: ['tenant_id'], episodic: ['tenant_id'] },
  },
})
await tenantMemory.connect()
// In AI SDK v7 a tool description may also be a function, so check it's a string before slicing it.
const tenantToolDescription = tenantMemory({ userId: 'u1', sessionId: 's1' }).memory.description
console.log('tenant-scoped tool commands:\n' + (typeof tenantToolDescription === 'string' ? tenantToolDescription : '').split('Commands:')[1]?.split('Rules:')[0])

// deno-lint-ignore no-explicit-any
const idx = (await mongo.db(DB_NAME + '_tenants').collection('facts').listSearchIndexes().toArray()) as any[]
console.log('vector index fields:', JSON.stringify(idx[0]?.latestDefinition?.fields?.map((f: Record<string, unknown>) => f.path ? { type: f.type, path: f.path } : { type: f.type, dims: f.numDimensions })))

// ══════════ cell 30 ══════════
const voyageLargeMemory = createMongoDBMemory({
  uri: MONGODB_URI,
  embedder: gateway.embeddingModel('voyage/voyage-4-large'),   // ← the only line that changed
  topology: { dbName: DB_NAME + '_voyage_large' },
})
await voyageLargeMemory.connect()
await voyageLargeMemory.store.semanticSave('probe', 'Probe', 'Dimension probe fact.')

for (const [label, db] of [['voyage-4-lite', DB_NAME], ['voyage-4-large', DB_NAME + '_voyage_large']] as const) {
  const doc = await mongo.db(db).collection('semantic_memory').findOne({}, { projection: { embedding: 1 } })
  // deno-lint-ignore no-explicit-any
  const vi = (await mongo.db(db).collection('semantic_memory').listSearchIndexes().toArray()) as any[]
  console.log(`${label.padEnd(24)} stored dims=${doc?.embedding?.length}  index dims=${vi[0]?.latestDefinition?.fields?.[0]?.numDimensions}`)
}

// ══════════ cell 31 ══════════
const CLEANUP_NOW: boolean = false   // ← flip to true to drop the lab databases
if (!CLEANUP_NOW) {
  console.log('⏭️  Skipped. Set CLEANUP_NOW = true to drop the lab databases.')
} else {
  for (const db of [DB_NAME, DB_NAME + '_tuned', DB_NAME + '_tenants', DB_NAME + '_voyage_large']) {
    await mongo.db(db).dropDatabase()
    console.log('dropped', db)
  }
}
await mongo.close()
await Promise.all([mongodbMemory, mongodbMemoryB, tunedMemory, tenantMemory, voyageLargeMemory].map((m) => m.close()))
console.log('✅ connections closed')

// ══════════ cell 32 ══════════
const DEPLOY_NOW: boolean = false   // ← flip to true to deploy
// Only if your Vercel login belongs to several teams: the team slug to deploy into (the script lists them).
const VERCEL_SCOPE = ''
let DEPLOY_URL = ''

if (!DEPLOY_NOW) {
  console.log('⏭️  Skipped. Set DEPLOY_NOW = true to deploy Trailhead to Vercel + Atlas.')
} else {
  // The notebook lives in labs/ or solutions/; deploy/ sits at the lab root next to them.
  const candidates = [`${Deno.cwd()}/deploy`, `${Deno.cwd()}/../deploy`]
  let deployDir = ''
  for (const dir of candidates) {
    try { await Deno.stat(`${dir}/deploy.sh`); deployDir = dir; break } catch { /* try the next one */ }
  }
  if (!deployDir) throw new Error(`deploy/deploy.sh not found from ${Deno.cwd()} — open the notebook from the lab folder`)

  // stdin: 'null' → no TTY → the script adds --non-interactive to every vercel command (never hangs on a prompt).
  const child = new Deno.Command('bash', {
    args: [`${deployDir}/deploy.sh`],
    stdin: 'null', stdout: 'piped', stderr: 'piped',
    env: { NO_COLOR: '1', VERCEL_SCOPE },
  }).spawn()

  // Stream both pipes line by line so progress shows up while the deploy runs.
  const pump = async (stream: ReadableStream<Uint8Array>) => {
    let buffer = ''
    const decoder = new TextDecoder()
    const handle = (line: string) => {
      const m = line.match(/^DEPLOY_URL=(https:\/\/[^\s"',]+)/)
      if (m) DEPLOY_URL = m[1]
      if (line.trim()) console.log(line)
    }
    for await (const bytes of stream) {
      const lines = (buffer + decoder.decode(bytes, { stream: true })).split(/\r?\n/)
      buffer = lines.pop() ?? ''
      lines.forEach(handle)
    }
    if (buffer) handle(buffer)
  }
  await Promise.all([pump(child.stdout), pump(child.stderr)])
  const { code } = await child.status
  if (code !== 0) throw new Error(`deploy.sh exited with code ${code} — read the ✖ hint above`)
  // Recorded for anything that checks the deployment afterwards (the hosted lab's check script reads it).
  await Deno.writeTextFile(`${deployDir}/.deploy-url`, DEPLOY_URL + '\n')
  console.log('\n🚀 Live at', DEPLOY_URL)
}

// ══════════ cell 33 ══════════
if (!DEPLOY_URL) {
  console.log('⏭️  No deployment yet — run the previous cell with DEPLOY_NOW = true.')
} else {
  const health = await (await fetch(`${DEPLOY_URL}/api/chat`)).json()
  console.log('✅ deployment healthy:', health)
  console.log(`\n👉 Open ${DEPLOY_URL} and chat with Trailhead`)
}
